apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.service.name}}
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  selector:
    app: {{ .Values.service.name }}